"""new fields in user model

Revision ID: 65389fb2c865
Revises: 32f4b58cc04d
Create Date: 2018-08-10 17:49:25.600610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65389fb2c865'
down_revision = '32f4b58cc04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
